# Generated by Django 4.0.2 on 2022-03-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='app/images/')),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('fav_count', models.IntegerField()),
                ('latest', models.DateField()),
                ('category', models.CharField(choices=[('FM', 'Fresh Meat'), ('V', 'Vegetables'), ('F&N', 'Fruit & Nut Gifts'), ('FB', 'Fresh Berries'), ('OF', 'Ocean Foods'), ('B&E', 'Butter & Eggs'), ('FF', 'Fastfood'), ('FO', 'Fresh Onion'), ('P%C', 'Papayaya & Crisps'), ('OM', 'Oatmeal'), ('B', 'Fresh Bananas')], max_length=3)),
            ],
        ),
    ]
