# Generated by Django 4.0.2 on 2022-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fav_count',
            field=models.IntegerField(blank=True),
        ),
    ]
