# Generated by Django 4.0.2 on 2022-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_product_image1_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortinfo',
            field=models.TextField(default='NA'),
        ),
    ]
